### ISSUE TITLE
EN Introduction edits

### ISSUE THREAD

**Issue by dfbg** [tebe6502/mad-assembler-mkdocs#5]
Here is an edited first paragraph to improve the grammar:

MADS is oriented towards users of QA, XASM and FA. The syntax is borrowed from QA, some macro commands and syntax come from XASM and Sparta DOS X (SDX) support is inherited from FA. Additional characters are allowed in label names. Support has been added for the WDC 65816 CPU, macros, procedures, memory partitioning into virtual memory banks and nested label names.

In the first paragraph of Compilation there is the typo "latested".

**Comment by mirao** [comment]
One more typo: "MADS **supportes** small additions to"
